#Library
library(readr)
library(tidyverse)
library(dbplyr)
library(lubridate)
library(Rmpfr)
#Seperate data for 1,2,3
brazil <- subset(owid_covid_data, location == "Brazil")
brazil <- subset(brazil, month(date) == 1 | month(date) == 7 | month(date) == 9 |month(date) == 10)
brazil.2020 <- subset(brazil, year(date) == 2020)
brazil.2021 <- subset(brazil, year(date) == 2021)
brazil.2022 <- subset(brazil, year(date) == 2022)
chile <- subset(owid_covid_data, location == "Chile")
chile <- subset(chile, month(date) == 1 | month(date) == 7 | month(date) == 9 |month(date) == 10)
chile.2020 <- subset(chile, year(date) == 2020)
chile.2021 <- subset(chile, year(date) == 2021)
chile.2022 <- subset(chile, year(date) == 2022)
venezuela <- subset(owid_covid_data, location == "Venezuela")
venezuela <- subset(venezuela, month(date) == 1 | month(date) == 7 | month(date) == 9 |month(date) == 10)
venezuela.2020 <- subset(venezuela, year(date) == 2020)
venezuela.2021 <- subset(venezuela, year(date) == 2021)
venezuela.2022 <- subset(venezuela, year(date) == 2022)