Brazil_data <- subset(countries_covid_group_data, location == "Brazil") 
    Status <- c("Min", "Q1", "Q2", "Q3", "Max", "Avg", "Std", "Outlier")
    Min=min(Brazil_data$new_cases) 
    Q1=quantile(Brazil_data$new_cases,0.25) 
    Q2=quantile(Brazil_data$new_cases,0.5) 
    Q3=quantile(Brazil_data$new_cases,0.75) 
    Max=max(Brazil_data$new_cases) 
    Avg=format(round(mean(Brazil_data$new_cases),2),2) 
    Std=format(round(sd(Brazil_data$new_cases),2),2)
    Outlier=sum(Brazil_data$new_cases<Q1-1.5*(Q3-Q1))+sum(Brazil_data$new_cases>Q3+1.5*(Q3-Q1))
    New_cases<-c(Min, Q1, Q2, Q3, Max, Avg, Std, Outlier)
    
    Min=min(Brazil_data$new_deaths) 
    Q1=quantile(Brazil_data$new_deaths,0.25) 
    Q2=quantile(Brazil_data$new_deaths,0.5) 
    Q3=quantile(Brazil_data$new_deaths,0.75) 
    Max=max(Brazil_data$new_deaths) 
    Avg=format(round(mean(Brazil_data$new_deaths),2),2) 
    Std=format(round(sd(Brazil_data$new_deaths),2),2)
    Outlier=sum(Brazil_data$new_deaths<Q1-1.5*(Q3-Q1))+sum(Brazil_data$new_deaths>Q3+1.5*(Q3-Q1))
    New_deaths<-c(Min, Q1, Q2, Q3, Max, Avg, Std, Outlier)
    
    output_Brazil <- data.frame(Status, New_cases, New_deaths)