ROW_NEWCASES_BRA <- c('Brazil', MIN_NEWCASES_BRA,Q1_Q2_Q3_NEWCASES_BRA[1],
                      Q1_Q2_Q3_NEWCASES_BRA[2],Q1_Q2_Q3_NEWCASES_BRA[3],
                      MAX_NEWCASES_BRA, AVG_NEWCASES_BRA,STD_NEWCASES_BRA,
                      OUTLIERS_NEWCASES_BRA)
ROW_NEWCASES_CHL <- c('Chile', MIN_NEWCASES_CHL,Q1_Q2_Q3_NEWCASES_CHL[1],
                      Q1_Q2_Q3_NEWCASES_CHL[2],Q1_Q2_Q3_NEWCASES_CHL[3],
                      MAX_NEWCASES_CHL, AVG_NEWCASES_CHL,STD_NEWCASES_CHL,
                      OUTLIERS_NEWCASES_CHL)
ROW_NEWCASES_VEN <- c('Venezuela', MIN_NEWCASES_VEN,Q1_Q2_Q3_NEWCASES_VEN[1],
                      Q1_Q2_Q3_NEWCASES_VEN[2],Q1_Q2_Q3_NEWCASES_VEN[3],
                      MAX_NEWCASES_VEN, AVG_NEWCASES_VEN,STD_NEWCASES_VEN,
                      OUTLIERS_NEWCASES_VEN)
NEWCASES_TABLE <- rbind(ROW_NEWCASES_BRA,ROW_NEWCASES_CHL,ROW_NEWCASES_VEN)
colnames(NEWCASES_TABLE) <- c('Countries', 'Min', 'Q1', 'Q2', 'Q3', 'Max', 'Avg', 'Std', 'Outlier')

View(NEWCASES_TABLE)
#NEWDEATHS:
ROW_NEWDEATHS_BRA <- c('Brazil', MIN_NEWDEATHS_BRA,Q1_Q2_Q3_NEWDEATHS_BRA[1],
                       Q1_Q2_Q3_NEWDEATHS_BRA[2],Q1_Q2_Q3_NEWDEATHS_BRA[3],
                       MAX_NEWDEATHS_BRA, AVG_NEWDEATHS_BRA,STD_NEWDEATHS_BRA,
                       OUTLIERS_NEWDEATHS_BRA)
ROW_NEWDEATHS_CHL <- c('Chile', MIN_NEWDEATHS_CHL,Q1_Q2_Q3_NEWDEATHS_CHL[1],
                       Q1_Q2_Q3_NEWDEATHS_CHL[2],Q1_Q2_Q3_NEWDEATHS_CHL[3],
                       MAX_NEWDEATHS_CHL, AVG_NEWDEATHS_CHL,STD_NEWDEATHS_CHL,
                       OUTLIERS_NEWDEATHS_CHL)
ROW_NEWDEATHS_VEN <- c('Venezuela', MIN_NEWDEATHS_VEN,Q1_Q2_Q3_NEWDEATHS_VEN[1],
                       Q1_Q2_Q3_NEWDEATHS_VEN[2],Q1_Q2_Q3_NEWDEATHS_VEN[3],
                       MAX_NEWDEATHS_VEN, AVG_NEWDEATHS_VEN,STD_NEWDEATHS_VEN,
                       OUTLIERS_NEWDEATHS_VEN)
NEWDEATHS_TABLE <- rbind(ROW_NEWDEATHS_BRA,ROW_NEWDEATHS_CHL,ROW_NEWDEATHS_VEN)
colnames(NEWDEATHS_TABLE) <- c('Countries', 'Min', 'Q1', 'Q2', 'Q3', 'Max', 'Avg', 'Std', 'Outlier')

View(NEWDEATHS_TABLE)
